# file: roles/certbot_standalone/tasks/main.yml
#
# Let's Encrypt recommended Certbot
#
---

- name: Check administrative email contact
  assert:
    that:
    - admin_email is defined
    - admin_email.strip() != ""

- name: Certbot Apache package
  when: ansible_pkg_mgr == "yum"
  with_items:
  - python-certbot-apache
  become: yes
  yum: name="{{ item }}" state=present

- debug: var=certbot_domains

- name: Configure Certbot for domains
  when:
    - certbot_domains is defined
    - certbot_domains | length > 0
  include: domains.yml
