---
# file: roles/dmz/tasks/main.yml

#
# Configures the other network interface of a guest to the DMZ.
#

- name: Get the default zone
  sudo: yes
  command: firewall-cmd --get-default-zone
  register: default_zone

- name: Query if there's another interface in the default zone
  sudo: yes
  command: firewall-cmd --zone={{ default_zone.stdout | mandatory }}
           --query-interface=eth1
  register: another_interface
  changed_when: (another_interface.rc == 0) and another_interface.stdout|bool
  failed_when: None

- name: Create the interface configuration file
  when: another_interface|changed
  sudo: yes
  template: src=ifcfg-eth1.j2 dest=/etc/sysconfig/network-scripts/ifcfg-eth1
            force=no mode=644

- name: Remove the other interface from the default zone
  when: another_interface|changed
  sudo: yes
  command: firewall-cmd --permanent --zone={{ default_zone.stdout }}
           --remove-interface=eth1
  notify: Restart the firewall

- name: Add the other interface to the DMZ
  when: another_interface|changed
  sudo: yes
  command: firewall-cmd --permanent --zone=dmz --add-interface=eth1
  notify: Restart the firewall

- name: Default route via the DMZ interface
  sudo: yes
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0
              regexp='^\s*DEFROUTE=' line='DEFROUTE=no'

- name: Restart the network
  when: another_interface|changed
  sudo: yes
  service: name=network state=restarted

#
# The permanent FirewallD configuration should be now fine, but an extra step
# is required to address a bug: https://bugs.centos.org/view.php?id=7526
#
- name: Change the other interface to the DMZ (to address CentOS-7 bug 7526)
  sudo: yes
  command: firewall-cmd --zone=dmz --change-interface=eth1

- name: Update Hetzner reverse DNS records
  when: public_hostname is defined and public_ipv4_address is defined
  no_log: True
  local_action: command curl -su
                '{{ hetzner_api_user | mandatory }}:{{ hetzner_api_password | mandatory }}'
                {{ hetzner_api_url }}/rdns/{{ (ansible_eth1|mandatory).ipv4.address }}
                -d 'ptr={{ public_hostname }}'
  register: hetzner_result
  failed_when: (hetzner_result.stdout|from_json).error is defined
