---
# file: local_dev_client.yml

#
# Development tools and keys for the service management domain
#

- hosts: localhost
  connection: local
  vars_files:
  - /mnt/sensitive_data/etc/ansible/vars/admin_access.yml
  roles:
  - transport_layer_security
  - ca_trust
  - ../../service_commons_ansible/java_keystore
  - maven
  - ../../service_commons_ansible/roles/updates_auto
