---
# file: web_servers.yml

#
# Web services and reverse proxies
#

- hosts: web_servers
  vars_files:
    - /mnt/sensitive_data/etc/ansible/vars/admin_access.yml
    - /mnt/sensitive_data/etc/ansible/vars/dynect.yml
    - /mnt/sensitive_data/etc/ansible/vars/hetzner.yml
  roles:
    - access_control
    - ca_trust
    - dmz
    - libvirt_guest_network_service
    - transport_layer_security
    - ../../service_commons_ansible/roles/updates_auto
    - https_virtual_proxies
