---
# file: wildfly8_servers.yml

#
# WildFly 8 Java EE Application Servers
#

- hosts: wildfly8_servers
  vars_files:
  - /mnt/sensitive_data/etc/ansible/vars/admin_access.yml
  roles:
  - libvirt_guest_network_service
  - transport_layer_security
  - hosts_aliases
  - java_oracle
  - ca_trust
  - java_keystore
  - wildfly8
  - wildfly8_logging
  - wildfly8_postgresql_drivers
  - wildfly8_datasources
  - wildfly8_mail
