---
# file: roles/jenkins_ci_backup/tasks/main.yml

#
# roles/jenkins_ci sets the jenkins_home variable.
#

- name: Jenkins CI backup excludes list
  sudo: yes
  copy: src=jenkins.backup_excludes
        dest="{{ jenkins_home | mandatory }}/.backup_excludes"
        mode=660 owner=jenkins group=jenkins

- name: Backup client configuration for Jenkins CI
  sudo: yes
  template: src=jenkins_ci.conf.j2
            dest="/usr/local/etc/backup_client.d/jenkins_ci.conf"

#
# Obsolete the older backup routine:
#

- name: Remove obsolete Jenkins backup script
  sudo: yes
  file: dest="{{ jenkins_home }}/backups/jenkins_backup.sh" state=absent
  register: obsolete_jenkins_backup

- name: Remove obsolete Jenkins backups directory
  sudo: yes
  file: dest="{{ jenkins_home }}/backups" state=absent

- name: Disable the obsolete Jenkins backup timer
  when: obsolete_jenkins_backup|changed
  sudo: yes
  command: systemctl disable jenkins_backup.timer
  ignore_errors: yes

- name: Stop the obsolete Jenkins backup timer
  when: obsolete_jenkins_backup|changed
  sudo: yes
  command: systemctl stop jenkins_backup.timer
  ignore_errors: yes

- name: Remove obsolete Jenkins backup service unit file
  sudo: yes
  file: dest=/etc/systemd/system/jenkins_backup.service state=absent

- name: Remove obsolete Jenkins backup timer unit file
  sudo: yes
  file: dest=/etc/systemd/system/jenkins_backup.timer state=absent
