---
# file: roles/jenkins_ci/handlers/main.yml

- name: Restart Jenkins
  sudo: yes
  service: name=jenkins state=restarted

- name: Restart firewalld
  sudo: yes
  service: name=firewalld state=restarted
