---
# file: roles/libvirt_guest_network_service/tasks/main.yml

#
# Disable NetworkManager
#

- name: Stop NetworkManager related services
  with_items:
  - NetworkManager-wait-online.service
  - NetworkManager.service
  sudo: yes
  shell: systemctl stop {{ item }}
  failed_when: False

- name: Disable NetworkManager related services
  with_items:
  - NetworkManager-wait-online.service
  - NetworkManager.service
  sudo: yes
  shell: systemctl disable {{ item }}

- name: /etc/sysconfig/network-scripts/ifcfg-X NM_CONTROLLED=no
  with_items:
  - eth0
  - eth1
  sudo: yes
  lineinfile:
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item }}"
    regexp: "^NM_CONTROLLED="
    line: "NM_CONTROLLED=no"
  failed_when: False

- name: /etc/sysconfig/network-scripts/ifcfg-X ONBOOT=yes
  with_items:
  - eth0
  - eth1
  sudo: yes
  lineinfile:
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item }}"
    regexp: "^ONBOOT="
    line: "ONBOOT=yes"
  failed_when: False

- name: Remove NetworkManager
  sudo: yes
  yum: name=NetworkManager state=absent

- name: Restart the network service
  sudo: yes
  service: name=network enabled=yes state=restarted
