---
# file: roles/jenkins_ci/tasks/main.yml

- name: Graphviz
  sudo: yes
  yum: name=graphviz

- name: Configure the Jenkins RPM repository
  sudo: yes
  get_url: dest=/etc/yum.repos.d/jenkins.repo
           url=http://pkg.jenkins-ci.org/redhat/jenkins.repo

#
# jenkins-ci.org key fingerprint: 150fde3f7787e7d11ef4e12a9b7d32f2d50582e6
# https://gist.github.com/kohsuke/10025805
# Note that there must be a newline after the --END PGP PUBLIC KEY BLOCK--
# marker in the key file. Otherwise rpm_key import will fail.
#
- name: Upload the Jenkins RPM repository GPG key
  sudo: yes
  copy: src=jenkins-ci.org.key dest=/root/jenkins-ci.org.key

- name: Import the Jenkins RPM repository GPG key
  sudo: yes
  rpm_key: key=/root/jenkins-ci.org.key state=present

- name: Ensure Jenkins CI is present
  sudo: yes
  yum: name=jenkins

- name: Find the Jenkins CI home directory
  sudo: yes
  shell: "cat /etc/passwd | grep '^jenkins:' | cut -d: -f6"
  register: jenkins_home
  failed_when: jenkins_home.stdout.strip() == ""
  changed_when: False

- set_fact:
    jenkins_home: "{{ jenkins_home.stdout.strip() }}"

- name: Generate SSH key for the jenkins user
  sudo: yes
  user: name=jenkins createhome=no
        generate_ssh_key=yes
        ssh_key_comment=jenkins@{{ ansible_fqdn }}-{{ ansible_date_time.iso8601 }}

- name: Copy admin known_hosts to jenkins user
  sudo: yes
  shell: cp -f /home/{{ admin_username }}/.ssh/known_hosts
         "{{ jenkins_home }}/.ssh/known_hosts"

- name: Jenkins known_hosts permissions
  sudo: yes
  file: dest="{{ jenkins_home }}/.ssh/known_hosts"
        owner=jenkins group=jenkins mode=600

#
# This allows Jenkins E-mail Notifications to use a TLS enabled SMTP server.
#
- name: Enable SMTP TLS for Jenkins
  sudo: yes
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: "^\\s*JENKINS_JAVA_OPTIONS\\s*=.*$"
    line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Dmail.smtp.starttls.enable={{ jenkins_smtp_tls | default("true") }}"'
  notify: Restart Jenkins

- name: Jenkins location configuration
  with_items:
  - tag: adminAddress
    val: "Jenkins &lt;{{ jenkins_system_email | mandatory }}&gt;"
  - tag: jenkinsUrl
    val: "https://{{ public_hostname | mandatory }}/"
  sudo: yes
  lineinfile:
    dest: "{{ jenkins_home }}/jenkins.model.JenkinsLocationConfiguration.xml"
    regexp: "^(\\s*<{{ item.tag | mandatory }}>).*(</{{ item.tag }}>)\\s*$"
    backrefs: yes
    line: "\\1{{ item.val | mandatory }}\\2"
  notify: Restart Jenkins

- name: Mailer configuration
  with_items:
  - tag: smtpAuthUsername
    val: "{{ jenkins_smtp_username | mandatory }}"
  - tag: smtpAuthPassword
    val: "{{ jenkins_smtp_password | mandatory }}"
  - tag: smtpHost
    val: "{{ jenkins_smtp_hostname | mandatory }}"
  - tag: useSsl
    val: "{{ jenkins_smtp_ssl | default('false') }}"
  - tag: smtpPort
    val: "{{ jenkins_smtp_port | mandatory }}"
  - tag: charset
    val: "UTF-8"
  sudo: yes
  lineinfile:
    dest: "{{ jenkins_home }}/hudson.tasks.Mailer.xml"
    regexp: "^(\\s*<{{ item.tag | mandatory }})>.*<(/{{ item.tag }}>)\\s*$"
    backrefs: yes
    line: "\\1>{{ item.val | mandatory }}<\\2"
  notify: Restart Jenkins

- name: Open firewall port 8080 access from within the libvirt default network
  sudo: yes
  command: firewall-cmd --permanent
           --add-rich-rule='rule family="ipv4"
           source address="192.168.122.0/24"
           port port="8080" protocol="tcp" accept'
  changed_when: False

- name: Reload the firewall
  sudo: yes
  command: firewall-cmd --reload
  changed_when: False

- name: Start Jenkins CI
  sudo: yes
  service: name=jenkins state=started enabled=yes

#
# Jenkins configuration is best done manually via the web console
# and then kept regularly backed up.
#
# Restore the Jenkins CI home directory from archives after redeployment.
#
