---
# file: roles/maven/tasks/main.yml

#
# Apache Maven
#

- name: Packages
  with_items:
  - maven
  sudo: yes
  yum: name={{ item }}

- name: Maven options
  sudo: yes
  copy: src=maven.sh dest=/etc/profile.d/maven.sh
        owner=root group=root mode=0644
