# file: roles/ldap_server/handlers/main.yml
---

- name: Restart the directory server
  become: yes
  service: name=slapd state=restarted

- name: Restart firewall
  become: yes
  service: name=firewalld state=restarted
