---
# file: roles/wildfly8_logging/tasks/main.yml

#
# WildFly 8 logging levels by category
#

- name: Check loggers
  when: wildfly8_loggers is defined
  sudo: yes
  sudo_user: "{{ wildfly8_user }}"
  command: chdir="{{ wildfly8_home | mandatory }}"
           {{ wildfly8_cli | mandatory }} --connect
           --command='/subsystem=logging:read-children-names(child-type=logger)'
           --timeout=200
  register: wildfly8_loggers_result

- name: Add loggers
  with_items: wildfly8_loggers | default([])
  when: "'{{ item.category }}' not in wildfly8_loggers_result.stdout"
  sudo: yes
  sudo_user: "{{ wildfly8_user }}"
  command: chdir="{{ wildfly8_home | mandatory }}"
           {{ wildfly8_cli | mandatory }} --connect
           --command='/subsystem=logging/logger={{ item.category | mandatory
           }}:add(category={{ item.category }},level={{ item.level | mandatory
           }})'

- name: Configure loggers
  with_items: wildfly8_loggers | default([])
  when: "'{{ item.category }}' in wildfly8_loggers_result.stdout"
  sudo: yes
  sudo_user: "{{ wildfly8_user }}"
  command: chdir="{{ wildfly8_home | mandatory }}"
           {{ wildfly8_cli | mandatory }} --connect
           --command='/subsystem=logging/logger={{ item.category | mandatory
           }}:write-attribute(name=level,value={{ item.level | mandatory }})'
