---
# file: roles/postfix_standalone/tasks/main.yml

#
# Amavisd-new pulls clamav, clamd and spamassassin as its dependencies
# The clamav-update package provides freshclam antivirus database updates
#
- name: Postfix, Amavisd-new, and Alpine packages
  with_items:
  - postfix
  - amavisd-new
  - clamav-update
  - alpine
  yum: name={{ item }}

#
# freshclam - virus database updates configuration
#

- name: Freshclam configuration
  lineinfile:
    dest:   /etc/freshclam.conf
    regexp: '^#?\s*Example'
    line:   '#Example'

- name: Freshclam database mirror
  lineinfile:
    dest:   /etc/freshclam.conf
    regexp: '^#?\s*DatabaseMirror\s*db\.[A-Za-z]+\.clamav\.net$'
    line:   'DatabaseMirror db.{{ network_country_code | mandatory }}.clamav.net'

#
# Amavisd configuration
#

- name: Amavisd concurrency
  lineinfile:
    dest:   /etc/amavisd/amavisd.conf
    regexp: ^\\$max_servers
    line:   $max_servers = '{{ amavis_max_servers | mandatory }}';
  notify:
    - Restart Postfix
    - Restart clamd@amavisd

- name: Amavisd domain
  lineinfile:
    dest:   /etc/amavisd/amavisd.conf
    regexp: ^\\$mydomain
    line:   $mydomain = '{{ postfix_mydomain | mandatory }}';
  notify:
    - Restart clamd@amavisd

- name: Amavisd hostname
  lineinfile:
    dest:        /etc/amavisd/amavisd.conf
    regexp:      ^\\$myhostname
    line:        $myhostname = '{{ postfix_myhostname | mandatory }}';
    insertafter: ^#\s+\\$myhostname
  notify:
    - Restart clamd@amavisd

- name: Amavisd helpers home
  lineinfile:
    dest:        /etc/amavisd/amavisd.conf
    regexp:      ^\\$helpers_home
    line:        $helpers_home = "$MYHOME/var";
    insertafter: ^#\s+\\$helpers_home
  notify:
    - Restart clamd@amavisd

#
# Postfix configuration
#

- name: Postfix disable soft_bounce
  lineinfile:
    dest:        /etc/postfix/main.cf
    regexp:      '^soft_bounce'
    line:        'soft_bounce = no'
    insertafter: '^#soft_bounce'
  notify:
    - Reload Postfix

- name: Postfix hostname
  lineinfile:
    dest:        /etc/postfix/main.cf
    regexp:      '^myhostname'
    line:        'myhostname = {{ postfix_myhostname | mandatory }}'
    insertafter: '^#myhostname'
  notify:
    - Reload Postfix

- name: Postfix domain
  lineinfile:
    dest:        /etc/postfix/main.cf
    regexp:      '^mydomain'
    line:        'mydomain = {{ postfix_mydomain | mandatory }}'
    insertafter: '^#mydomain'
  notify:
    - Reload Postfix

- name: Postfix interfaces
  lineinfile:
    dest:        /etc/postfix/main.cf
    regexp:      '^inet_interfaces'
    line:        'inet_interfaces = all'
    insertafter: '^#inet_interfaces'
  notify:
    - Reload Postfix

- name: Postfix destination
  when: postfix_mydestination is defined
  lineinfile:
    dest:        /etc/postfix/main.cf
    regexp:      '^mydestination'
    line:        'mydestination = {{ postfix_mydestination | mandatory }}'
    insertafter: '^#mydestination'
  notify:
    - Reload Postfix

- name: Postfix networks style
  lineinfile:
    dest:         /etc/postfix/main.cf
    regexp:       '^mynetworks_style'
    line:         'mynetworks_style = host'
    insertafter:  '^#mynetworks_style'
  notify:
    - Reload Postfix

- name: Postfix origin
  lineinfile:
    dest:         /etc/postfix/main.cf
    regexp:       '^myorigin'
    line:         'myorigin = $mydomain'
    insertafter:  '^#myorigin'
  notify:
    - Reload Postfix

- name: Postfix networks
  when: postfix_mynetworks is defined
  lineinfile:
    dest:         /etc/postfix/main.cf
    regexp:       '^mynetworks'
    line:         'mynetworks = {{ postfix_mynetworks | mandatory }}'
    insertafter:  '^#mynetworks'
  notify:
    - Reload Postfix

- name: Postfix relay host
  when: postfix_relayhost is defined
  lineinfile:
    dest:         /etc/postfix/main.cf
    regexp:       '^relayhost'
    line:         'relayhost = {{ postfix_relayhost | mandatory }}'
    insertafter:  '^#relayhost'
  notify:
    - Reload Postfix

#
# Postfix TLS Support - http://www.postfix.org/TLS_README.html
#

#
# roles/transport_layer_security deploys the certificates and keys
# http://www.postfix.org/TLS_README.html#server_cert_key
#
- name: Postfix TLS server-side certificate and private key 
  when: public_hostname_certificate|skipped or
        not public_hostname_certificate.stat.exists
  fail: msg="Need a X.509 certificate for {{ public_hostname }}"

- name: Postfix TLS RSA certificate
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: '^smtpd_tls_cert_file'
    line:   'smtpd_tls_cert_file = /etc/pki/tls/certs/{{ public_hostname | mandatory }}-crt.pem'
  notify:
    - Reload Postfix

- name: Postfix TLS RSA key
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: '^smtpd_tls_key_file'
    line:   'smtpd_tls_key_file = /etc/pki/tls/private/{{ public_hostname | mandatory }}-key.pem'
  notify:
    - Reload Postfix

- name: Postfix TLS mandatory ciphers
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: '^smtpd_tls_mandatory_ciphers'
    line:   'smtpd_tls_mandatory_ciphers = high'
  notify:
    - Reload Postfix

- name: Postfix TLS mandatory exclude ciphers
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: '^smtpd_tls_mandatory_exclude_ciphers'
    line:   'smtpd_tls_mandatory_exclude_ciphers = aNULL, MD5'
  notify:
    - Reload Postfix

#
# http://www.postfix.org/postconf.5.html#smtpd_tls_security_level
#
- name: Postfix TLS security level
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: '^smtpd_tls_security_level'
    line:   'smtpd_tls_security_level = may'
  notify:
    - Reload Postfix

- name: Postfix TLS mandatory protocols
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: '^smtpd_tls_mandatory_protocols'
    line:   'smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3'
  notify:
    - Reload Postfix

#
# Postfix master configuration
#
- name: Postfix master.cf
  template:
    src:   master.cf.j2
    dest:  /etc/postfix/master.cf
    owner: root
    group: root
    mode:  0644
  notify:
    - Reload Postfix

- name: Disable the spamassassin service
  service: name=spamassassin enabled=no state=stopped

- name: Enable the clamd@amavisd service
  service: name=clamd@amavisd enabled=yes state=started

- name: Enable the amavisd service
  service: name=amavisd enabled=yes state=started

- name: Enable the Postfix service
  service: name=postfix enabled=yes state=started

#
# http://wiki.centos.org/HowTos/Amavisd
#
- name: Postfix content filter
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: '^content_filter'
    line:   'content_filter = amavisfeed:[127.0.0.1]:10024'
  notify:
    - Restart Postfix

#
# Firewall zone services and ports
#

- name: Query if the SMTP service has been added to the firewall zone
  command: firewall-cmd --zone={{ firewall_zone | mandatory }}
           --query-service=smtp
  register: zone_smtp
  changed_when: (zone_smtp.rc != 0) or not zone_smtp.stdout|bool
  failed_when: None

- name: Open the firewall for the SMTP service
  when: zone_smtp|changed
  command: firewall-cmd --permanent --zone={{ firewall_zone | mandatory }}
           --add-service=smtp
  notify: Reload the firewall

- name: Query if the Message Submission service has been added to the firewall zone
  command: firewall-cmd --zone={{ firewall_zone | mandatory }}
           --query-port=587/tcp
  register: zone_submission
  changed_when: (zone_submission.rc != 0) or not zone_submission.stdout|bool
  failed_when: None

- name: Open the firewall for the Message Submission service
  when: zone_submission|changed
  command: firewall-cmd --permanent --zone={{ firewall_zone | mandatory }}
           --add-port=587/tcp
  notify: Reload the firewall
