# file: roles/archive_keys/tasks/main.yml

#
# PKI-based security for the application data archives
#

- name: Archive keys directory
  sudo: yes
  sudo_user: "{{ backup_user | mandatory }}"
  file: state=directory path="/{{ archive_keys_path | mandatory }}/client"
        owner="{{ backup_user }}" group="{{ backup_user }}" mode=750

# http://security.stackexchange.com/questions/2335/should-rsa-public-exponent-be-only-in-3-5-17-257-or-65537-due-to-security-c
# http://crypto.stackexchange.com/questions/3110/impacts-of-not-using-rsa-exponent-of-65537

- name: Backup client private key (this may take a while)
  sudo: yes
  sudo_user: "{{ backup_user }}"
  command: chdir="/{{ archive_keys_path }}/client"
           creates="{{ ansible_fqdn }}_backup-client-private.pem"
           openssl genpkey -algorithm RSA
           -out "{{ ansible_fqdn }}_backup-client-private.pem" -outform PEM
           -pkeyopt rsa_keygen_bits:{{ archive_key_length | mandatory }}
           -pkeyopt rsa_keygen_pubexp:65537

- name: Backup client private key permissions
  sudo: yes
  sudo_user: "{{ backup_user }}"
  file: path="/{{ archive_keys_path }}/client/{{ ansible_fqdn }}_backup-client-private.pem"
        owner={{ backup_user }} group={{ backup_user }} mode=0400

- name: Backup client public key
  sudo: yes
  sudo_user: "{{ backup_user }}"
  command: chdir="/{{ archive_keys_path }}/client"
           creates="{{ ansible_fqdn }}_backup-client-public.pem"
           openssl rsa
           -in "{{ ansible_fqdn }}_backup-client-private.pem"
           -out "{{ ansible_fqdn }}_backup-client-public.pem"
           -outform PEM -pubout

- name: Backup client public key permissions
  sudo: yes
  sudo_user: "{{ backup_user }}"
  file: path="/{{ archive_keys_path }}/client/{{ ansible_fqdn }}_backup-client-public.pem"
        owner={{ backup_user }} group={{ backup_user }} mode=0444

- name: Archives public key
  sudo: yes
  sudo_user: "{{ backup_user }}"
  copy:
    content: "{{ archives_public_key | mandatory }}"
    dest:    "/{{ archive_keys_path }}/archives-public.pem"
    owner:   "{{ backup_user }}"
    group:   "{{ backup_user }}"
    mode:    0444

#
# The archives-private.pem is kept offline and generated manually.
# DO NOT copy the archives private key to /mnt/sensitive_data/.
#
